### ISSUE TITLE
The separate Edinburgh TM page still mentions Appleton Tower

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/techmeetup.co.uk#16]
This page http://techmeetup.co.uk/edinburgh.html still mentions Appleton Tower as the usual location for Techmeetup.
We should update that page to mention Skyscanner's address.
I think we can do that by adding the location to http://opentechcalendar.co.uk/event/891-welcoming-anyone-involvedworking-in-technology  @jarofgreen ?

**Comment by jarofgreen** [comment]
If you mean the paragraph of text at the bottom about how to get into the venue, that's just static HTML, update the Jekyll site.

**Comment by MariusCiocanel** [comment]
If you look on  http://techmeetup.co.uk/edinburgh.html you'll see that for the May 2014 event has the Appleton Tower address.
If want to add Skyscanner's address to the April 2014 event on that page I'll have to update the OpenTechCalendar event, right?

**Comment by jarofgreen** [comment]
That page shows the description text for the event I think.  So yes, you can edit the description of the event to add the address.

**Comment by jarofgreen** [comment]
Btw I made sure the js that builds that page is on TM site not OTC so you can can edit it freely if you want to change anything

**Comment by MikeMcQuaid** [comment]
Looks like this was done.
