### ISSUE TITLE
Glasgow meetup on September 23rd?

### ISSUE THREAD

**Issue by cobyism** [techmeetup/techmeetup.co.uk#37]
I’m considering going along to the Glasgow TechMeetup if it’s on tomorrow night (23rd is the 4th Wednesday of September, right?), but the website doesn’t seem to have been updated:

<img width="347" alt="2015-09-22 at 13 10" src="https://cloud.githubusercontent.com/assets/296432/10018063/85a7af6e-612b-11e5-82b2-2dc9dcba25b1.png">

Any chance of an update?

**Comment by KevinBrolly** [comment]
Hi!

Sorry this month has been cancelled!  I just had a baby and have had no time to organise.  We updated the mailing list and tweeted but forgot the website, it is updated now, thanks for letting us know!

Do come along next month on 28th October!

**Comment by cobyism** [comment]
:+1: Cool, thanks for the update @KevinBrolly. Oh, and congratulations on the new human! :baby_bottle: :zap: :sparkles:
